export interface PortfolioType {
    id?: number;
    userName: string;
    first_name?: string;
    last_name?: string;
    about?: string;
    is_seeking_job?: boolean;
    is_working?: boolean;
    employer?: string;
    nationality?: string;
    country_residence?: string;
    mobile_number?: string;
    github?: string;
    linkedin?: string;
    twitter?: string;
    gender?: string;
    fav_language?: string;
    employment_time?: string;
    personal_site?: string;
    proud_project?: string;
    email?: string;
    academic_qualification?: string;
    profile_image?: string;
    jobTitle?: string;
    years_experience?: number;
    created_at?: string;
    updated_at?: string;
    user?: number;
}